Fixed Order model lose `created_at` property.
slince/shopify-php-sdk pull request #55
Opened 2019-12-05 06:58 UTC by hiscaler

2019-12-08 22:02 UTC, maximzasorin commented
Hello, thanks for your commit. In your commit you have added a receipt field definition for the Fulfillment model. Where did you get this definition? The API documentation has a completely [different definition](https://help.shopify.com/en/api/reference/shipping-and-fulfillment/fulfillment#receipt-property-2019-10), maybe there is an error in the documentation, but how to check yours? How can I create Fulfillment with receipt field?

2019-12-09 02:50 UTC, hiscaler commented
@maximzasorin I get from orders admin api. response data like follow:
```json
{
    "receipt": {
        "gift_cards": [
            {
                "id": 111,
                "line_item_id": 222,
                "masked_code": "•••• •••• •••• 333"
            }
        ]
    }
}
```

2019-12-10 18:36 UTC, maximzasorin commented
@hiscaler 

I think we should clarify with the support or somewhere else this discrepancy. Maybe the value of this field does not have a constant format and depends on something, for example, as in the case of the receipt field for Transaction: https://help.shopify.com/en/api/reference/orders/transaction#receipt-property-2019-10

2019-12-11 01:56 UTC, hiscaler commented
@maximzasorin Maybe, but i not add it, parse will be throw error.

2020-12-14 13:53 UTC, jstoone requested changes
### General
These are great changs! :tada:

In #90 I added missing return statements to the setters of other models, which allows for a fluent method chaining. So I've suggested some changes to align your changes with mine. :relaxed: :v:

2020-12-14 13:53 UTC, jstoone commented on src/Manager/Order/GiftCard.php
> +     * @param int $id
```suggestion
     * @param int $id
     *
     * @return GiftCard
```

2020-12-14 13:53 UTC, jstoone commented on src/Manager/Order/GiftCard.php
> +        $this->id = $id;
```suggestion
        $this->id = $id;
        
        return $this;
```

2020-12-14 13:53 UTC, jstoone commented on src/Manager/Order/GiftCard.php
> +     * @param int $linnItemId
```suggestion
     * @param int $linnItemId
     *
     * @return GiftCard
```

2020-12-14 13:53 UTC, jstoone commented on src/Manager/Order/GiftCard.php
> +        $this->linnItemId = $linnItemId;
```suggestion
        $this->linnItemId = $linnItemId;
        
        return $this;
```

2020-12-14 13:53 UTC, jstoone commented on src/Manager/Order/GiftCard.php
> +     * @param string $maskedCode
```suggestion
     * @param string $maskedCode
     *
     * @return GiftCard
```

2020-12-14 13:53 UTC, jstoone commented on src/Manager/Order/GiftCard.php
> +        $this->maskedCode = $maskedCode;
```suggestion
        $this->maskedCode = $maskedCode;
        
        return $this;
```

2020-12-17 04:49 UTC, slince commented
2.x version is coming to an end; can you send pr to 3.x branch？

2020-12-17 04:49 UTC, closed without merging